name: flutter_no_internet_widget
description: A new Flutter widget to show online or offline widget without any
  extra code or dependencies.
version: 0.0.3+9
homepage: https://github.com/NaagAlgates/flutter_no_internet_widget

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  connectivity_plus: ^2.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  mocktail: ^0.3.0
  responsive_sizer: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
